/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reto5.vista;

/**
 *
 * @author Jaiver
 * 
 * El siguiente archivo crea la ventana principal, mediante la cual el usuario puede dirigirse a la informacion que necesite del restaurante
 * cada boton tiene una funcion para enviar al usuario a las diferentes ventas o tablas que necesite.
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ventanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        // se inician los componentes de la ventana principal
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo_venta_principal = new javax.swing.JLabel();
        jB_Mostrar_Clientes = new javax.swing.JButton();
        jB_Ingresar_Cliente_Menu_Principal = new javax.swing.JButton();
        jB_Mostrar_Meseros = new javax.swing.JButton();
        jB_Agregar_Mesero = new javax.swing.JButton();
        jBOrden = new javax.swing.JButton();
        jBTipoPlatos = new javax.swing.JButton();
        jBOrden_Agregar = new javax.swing.JButton();
        jB_Salir = new javax.swing.JButton();
        jBPlatos = new javax.swing.JButton();
        jBPlatosMostrar = new javax.swing.JButton();
        jBTipoPlatosAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo_venta_principal.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        Titulo_venta_principal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo_venta_principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/restaurant (1).png"))); // NOI18N
        Titulo_venta_principal.setText("Base de datos restaurante");
        Titulo_venta_principal.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jB_Mostrar_Clientes.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jB_Mostrar_Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user (1).png"))); // NOI18N
        jB_Mostrar_Clientes.setText("Mostrar Clientes");
        jB_Mostrar_Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_Mostrar_ClientesMouseClicked(evt);
            }
        });
        jB_Mostrar_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Mostrar_ClientesActionPerformed(evt);
            }
        });

        jB_Ingresar_Cliente_Menu_Principal.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jB_Ingresar_Cliente_Menu_Principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user (1).png"))); // NOI18N
        jB_Ingresar_Cliente_Menu_Principal.setText("Agregar Cliente");
        jB_Ingresar_Cliente_Menu_Principal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_Ingresar_Cliente_Menu_PrincipalMouseClicked(evt);
            }
        });
        jB_Ingresar_Cliente_Menu_Principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Ingresar_Cliente_Menu_PrincipalActionPerformed(evt);
            }
        });

        jB_Mostrar_Meseros.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jB_Mostrar_Meseros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/waiter.png"))); // NOI18N
        jB_Mostrar_Meseros.setText("Mostrar Meseros");
        jB_Mostrar_Meseros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Mostrar_MeserosActionPerformed(evt);
            }
        });

        jB_Agregar_Mesero.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jB_Agregar_Mesero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/waiter.png"))); // NOI18N
        jB_Agregar_Mesero.setText("Agregar Mesero");
        jB_Agregar_Mesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Agregar_MeseroActionPerformed(evt);
            }
        });

        jBOrden.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jBOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clipboard.png"))); // NOI18N
        jBOrden.setText("Mostrar Órdenes");
        jBOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOrdenActionPerformed(evt);
            }
        });

        jBTipoPlatos.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jBTipoPlatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/skewer (1).png"))); // NOI18N
        jBTipoPlatos.setText("Mostrar tipos de platos");
        jBTipoPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTipoPlatosActionPerformed(evt);
            }
        });

        jBOrden_Agregar.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jBOrden_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clipboard.png"))); // NOI18N
        jBOrden_Agregar.setText("Agregar Orden");
        jBOrden_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOrden_AgregarActionPerformed(evt);
            }
        });

        jB_Salir.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jB_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        jB_Salir.setText("Salir");
        jB_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_SalirActionPerformed(evt);
            }
        });

        jBPlatos.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jBPlatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dish-fork-and-knife (1).png"))); // NOI18N
        jBPlatos.setText("Mostrar Platos");
        jBPlatos.setToolTipText("");
        jBPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPlatosActionPerformed(evt);
            }
        });

        jBPlatosMostrar.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jBPlatosMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dish-fork-and-knife (1).png"))); // NOI18N
        jBPlatosMostrar.setText("Agregar Plato");
        jBPlatosMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPlatosMostrarActionPerformed(evt);
            }
        });

        jBTipoPlatosAgregar.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jBTipoPlatosAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/skewer (1).png"))); // NOI18N
        jBTipoPlatosAgregar.setText("Ingresar un Tipo de Plato");
        jBTipoPlatosAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTipoPlatosAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBOrden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jB_Mostrar_Meseros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Titulo_venta_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(jB_Mostrar_Clientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jB_Ingresar_Cliente_Menu_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jB_Agregar_Mesero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBTipoPlatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBOrden_Agregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jB_Salir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBPlatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBPlatosMostrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBTipoPlatosAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo_venta_principal)
                .addGap(18, 18, 18)
                .addComponent(jB_Mostrar_Clientes)
                .addGap(18, 18, 18)
                .addComponent(jB_Ingresar_Cliente_Menu_Principal)
                .addGap(18, 18, 18)
                .addComponent(jB_Mostrar_Meseros)
                .addGap(18, 18, 18)
                .addComponent(jB_Agregar_Mesero)
                .addGap(18, 18, 18)
                .addComponent(jBOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBOrden_Agregar)
                .addGap(18, 18, 18)
                .addComponent(jBPlatos)
                .addGap(18, 18, 18)
                .addComponent(jBPlatosMostrar)
                .addGap(18, 18, 18)
                .addComponent(jBTipoPlatos)
                .addGap(18, 18, 18)
                .addComponent(jBTipoPlatosAgregar)
                .addGap(18, 18, 18)
                .addComponent(jB_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_Mostrar_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Mostrar_ClientesActionPerformed

    }//GEN-LAST:event_jB_Mostrar_ClientesActionPerformed

    private void jB_Mostrar_ClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_Mostrar_ClientesMouseClicked
        VistaClientes vistaCliente = new VistaClientes(); // crea la instancia de la ventana vista Cliente donde se puede ver la tabla de clientes
        vistaCliente.setVisible(true);
    }//GEN-LAST:event_jB_Mostrar_ClientesMouseClicked

    private void jB_Ingresar_Cliente_Menu_PrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Ingresar_Cliente_Menu_PrincipalActionPerformed
         VistaInsertarCliente vistaICliente = new VistaInsertarCliente(); // crea la instancia de la ventana vista insertar Cliente
        vistaICliente.setVisible(true);
    }//GEN-LAST:event_jB_Ingresar_Cliente_Menu_PrincipalActionPerformed

    private void jB_Ingresar_Cliente_Menu_PrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_Ingresar_Cliente_Menu_PrincipalMouseClicked
     
    }//GEN-LAST:event_jB_Ingresar_Cliente_Menu_PrincipalMouseClicked

    private void jB_Mostrar_MeserosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Mostrar_MeserosActionPerformed
        VistaMeseros vistaMeseros = new VistaMeseros(); // crea la instancia de la ventana vista Meseros donde se puede ver la tabla de meseros
        vistaMeseros.setVisible(true);
    }//GEN-LAST:event_jB_Mostrar_MeserosActionPerformed

    private void jB_Agregar_MeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Agregar_MeseroActionPerformed
        VistaInsertarMesero vistaMesero = new VistaInsertarMesero();// crea la instancia de la ventana vista insertar mesero
        vistaMesero.setVisible(true);
    }//GEN-LAST:event_jB_Agregar_MeseroActionPerformed

    private void jBOrden_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOrden_AgregarActionPerformed
        VistaInsertarOrden vistaOrden = new VistaInsertarOrden(); //crea la instancia de la ventana vista insertar orden
        vistaOrden.setVisible(true);
    }//GEN-LAST:event_jBOrden_AgregarActionPerformed

    private void jB_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_SalirActionPerformed
        this.dispose(); //boton de salida
    }//GEN-LAST:event_jB_SalirActionPerformed

    private void jBOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOrdenActionPerformed
        VistaOrden vistaOrdenes = new VistaOrden(); // crea la instancia de la ventana vista ordenes donde se puede ver la tabla de ordenes
        vistaOrdenes.setVisible(true);
    }//GEN-LAST:event_jBOrdenActionPerformed

    private void jBPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPlatosActionPerformed
       VistaPlato vistaPlatos = new VistaPlato(); // crea la instancia de la ventana vista Platos donde se puede ver la tabla de platos
       vistaPlatos.setVisible(true);
    }//GEN-LAST:event_jBPlatosActionPerformed
 
    private void jBTipoPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTipoPlatosActionPerformed
      VistaTipoPlato vistaTipoPlato = new VistaTipoPlato(); // crea la instancia de la ventana vista tipo plato donde se puede ver la tabla de tipos de plato
      vistaTipoPlato.setVisible(true);       
    }//GEN-LAST:event_jBTipoPlatosActionPerformed

    private void jBPlatosMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPlatosMostrarActionPerformed
         VistaInsertarPlato vistaPlato = new VistaInsertarPlato(); // crea la instancia de la ventana vista insertar plato
        vistaPlato.setVisible(true);
    }//GEN-LAST:event_jBPlatosMostrarActionPerformed

    private void jBTipoPlatosAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTipoPlatosAgregarActionPerformed
         VistaInsertarTipoPlato vistaTipoPlato = new VistaInsertarTipoPlato(); //crea la isntancia de la ventana vista insertar tipo de plato
        vistaTipoPlato.setVisible(true);
    }//GEN-LAST:event_jBTipoPlatosAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo_venta_principal;
    private javax.swing.JButton jBOrden;
    private javax.swing.JButton jBOrden_Agregar;
    private javax.swing.JButton jBPlatos;
    private javax.swing.JButton jBPlatosMostrar;
    private javax.swing.JButton jBTipoPlatos;
    private javax.swing.JButton jBTipoPlatosAgregar;
    private javax.swing.JButton jB_Agregar_Mesero;
    private javax.swing.JButton jB_Ingresar_Cliente_Menu_Principal;
    private javax.swing.JButton jB_Mostrar_Clientes;
    private javax.swing.JButton jB_Mostrar_Meseros;
    private javax.swing.JButton jB_Salir;
    // End of variables declaration//GEN-END:variables
}
