/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reto5.vista;

import java.util.List;
import reto5.controlador.ClienteControlador;
import reto5.modelo.Cliente;

/**
 *
 * @author Jaiver
 * El siguiente archivo crea la ventana vista Clientes donde se encuentra la tabla de clientes 
 */
public class VistaClientes extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    public VistaClientes() {
        initComponents();
        mostrarClientes();
    }
    
    public void mostrarClientes(){
        ClienteControlador control = new ClienteControlador();
        List<Cliente> clientes = control.obtenerTodosLosClientes();
        ModeloTablaCliente modeloTabla = new ModeloTablaCliente(clientes); //se adjunta el modelo de tabla para clientes
        TablaClientes.setModel(modeloTabla);
        TablaClientes.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaClientes = new javax.swing.JTable();
        jB_Cerrar_Tbclientes = new javax.swing.JButton();
        jB_Editar_Tbclientes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(TablaClientes);

        jB_Cerrar_Tbclientes.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jB_Cerrar_Tbclientes.setText("Cerrar");
        jB_Cerrar_Tbclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_Cerrar_TbclientesMouseClicked(evt);
            }
        });
        jB_Cerrar_Tbclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Cerrar_TbclientesActionPerformed(evt);
            }
        });

        jB_Editar_Tbclientes.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jB_Editar_Tbclientes.setText("Editar");
        jB_Editar_Tbclientes.setToolTipText("");
        jB_Editar_Tbclientes.setActionCommand("");
        jB_Editar_Tbclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_Editar_TbclientesMouseClicked(evt);
            }
        });
        jB_Editar_Tbclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Editar_TbclientesActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user (1).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jB_Editar_Tbclientes)
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jB_Cerrar_Tbclientes)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jB_Editar_Tbclientes)
                        .addComponent(jB_Cerrar_Tbclientes)))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_Cerrar_TbclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_Cerrar_TbclientesMouseClicked
        this.dispose(); //cierra la ventana
    }//GEN-LAST:event_jB_Cerrar_TbclientesMouseClicked

    private void jB_Cerrar_TbclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Cerrar_TbclientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_Cerrar_TbclientesActionPerformed

    private void jB_Editar_TbclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Editar_TbclientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_Editar_TbclientesActionPerformed

    private void jB_Editar_TbclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_Editar_TbclientesMouseClicked
        Integer id = (Integer) TablaClientes.getModel().getValueAt(TablaClientes.getSelectedRow(), 0);
        ClienteControlador control = new ClienteControlador();
        Cliente cliente = control.obtenerClientePorId(id);
        VistaInsertarCliente vInsertarCliente = new VistaInsertarCliente(cliente, this); //inicia la instancia vista insertar cliente en caso de modificar un cliente
        vInsertarCliente.setVisible(true);
        
    }//GEN-LAST:event_jB_Editar_TbclientesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaClientes;
    private javax.swing.JButton jB_Cerrar_Tbclientes;
    private javax.swing.JButton jB_Editar_Tbclientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
