/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reto5.vista;

import java.util.List;
import reto5.controlador.MeseroControlador;
import reto5.modelo.Mesero;

/**
 *
 * @author Jaiver
 * El siguiente archivo crea la ventana vista Meseros donde se encuentra la tabla de meseros 
 */
public class VistaMeseros extends javax.swing.JFrame {

    /**
     * Creates new form Meseros
     */
    public VistaMeseros() {
        initComponents();
        mostrarMeseros();
    }
    
    public void mostrarMeseros(){
        MeseroControlador control = new MeseroControlador();
        List<Mesero> meseros = control.obtenerTodosLosMeseros();
        ModeloTablaMesero modeloTabla = new ModeloTablaMesero(meseros);//se adjunta el modelo de tabla para clientes
        JT_Tabla_Meseros.setModel(modeloTabla);
        JT_Tabla_Meseros.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JT_Tabla_Meseros = new javax.swing.JTable();
        jB_Cerrar_Tbmeseros = new javax.swing.JButton();
        jB_Editar_Tbmeseros = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(JT_Tabla_Meseros);

        jB_Cerrar_Tbmeseros.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jB_Cerrar_Tbmeseros.setText("Cerrar");
        jB_Cerrar_Tbmeseros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_Cerrar_TbmeserosMouseClicked(evt);
            }
        });
        jB_Cerrar_Tbmeseros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Cerrar_TbmeserosActionPerformed(evt);
            }
        });

        jB_Editar_Tbmeseros.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jB_Editar_Tbmeseros.setText("Editar");
        jB_Editar_Tbmeseros.setToolTipText("");
        jB_Editar_Tbmeseros.setActionCommand("");
        jB_Editar_Tbmeseros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_Editar_TbmeserosMouseClicked(evt);
            }
        });
        jB_Editar_Tbmeseros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Editar_TbmeserosActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/waiter.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jB_Editar_Tbmeseros)
                        .addGap(207, 207, 207)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jB_Cerrar_Tbmeseros)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Editar_Tbmeseros)
                    .addComponent(jB_Cerrar_Tbmeseros)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_Cerrar_TbmeserosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_Cerrar_TbmeserosMouseClicked
        this.dispose();
    }//GEN-LAST:event_jB_Cerrar_TbmeserosMouseClicked

    private void jB_Cerrar_TbmeserosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Cerrar_TbmeserosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_Cerrar_TbmeserosActionPerformed

    private void jB_Editar_TbmeserosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Editar_TbmeserosActionPerformed
        Integer id = (Integer) JT_Tabla_Meseros.getModel().getValueAt(JT_Tabla_Meseros.getSelectedRow(), 0);
        MeseroControlador control = new MeseroControlador();
        Mesero mesero = control.obtenerMeseroPorId(id);
        VistaInsertarMesero vInsertarMesero = new VistaInsertarMesero(mesero, this);//inicia la instancia vista insertar cliente en caso de modificar un mesero
        vInsertarMesero.setVisible(true);
    }//GEN-LAST:event_jB_Editar_TbmeserosActionPerformed

    private void jB_Editar_TbmeserosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_Editar_TbmeserosMouseClicked

    }//GEN-LAST:event_jB_Editar_TbmeserosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMeseros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMeseros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMeseros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMeseros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMeseros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JT_Tabla_Meseros;
    private javax.swing.JButton jB_Cerrar_Tbmeseros;
    private javax.swing.JButton jB_Editar_Tbmeseros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
