/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reto5.vista;

import java.util.List;
import reto5.controlador.OrdenControlador;
import reto5.modelo.Orden;

/**
 *
 * @author Jaiver
 * * El siguiente archivo crea la ventana vista Orden donde se encuentra la tabla de ordenes 
 */
public class VistaOrden extends javax.swing.JFrame {

    /**
     * Creates new form Orden
     */
    public VistaOrden() {
        initComponents();
        mostrarOrdenes();
    }
    
    public void mostrarOrdenes(){
        OrdenControlador control = new OrdenControlador();
        List<Orden> ordenes = control.obtenerTodasLasOrdenes();
        ModeloTablaOrden modeloTabla = new ModeloTablaOrden(ordenes);
        JT_Tabla_Ordenes.setModel(modeloTabla);
        JT_Tabla_Ordenes.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JT_Tabla_Ordenes = new javax.swing.JTable();
        jB_Cerrar_TbOrden = new javax.swing.JButton();
        jB_Editar_TbOrden = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(JT_Tabla_Ordenes);

        jB_Cerrar_TbOrden.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jB_Cerrar_TbOrden.setText("Cerrar");
        jB_Cerrar_TbOrden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_Cerrar_TbOrdenMouseClicked(evt);
            }
        });
        jB_Cerrar_TbOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Cerrar_TbOrdenActionPerformed(evt);
            }
        });

        jB_Editar_TbOrden.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jB_Editar_TbOrden.setText("Editar");
        jB_Editar_TbOrden.setToolTipText("");
        jB_Editar_TbOrden.setActionCommand("");
        jB_Editar_TbOrden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_Editar_TbOrdenMouseClicked(evt);
            }
        });
        jB_Editar_TbOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Editar_TbOrdenActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clipboard.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jB_Editar_TbOrden)
                        .addGap(207, 207, 207)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jB_Cerrar_TbOrden)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Editar_TbOrden)
                    .addComponent(jB_Cerrar_TbOrden)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_Cerrar_TbOrdenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_Cerrar_TbOrdenMouseClicked
        this.dispose();
    }//GEN-LAST:event_jB_Cerrar_TbOrdenMouseClicked

    private void jB_Cerrar_TbOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Cerrar_TbOrdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_Cerrar_TbOrdenActionPerformed

    private void jB_Editar_TbOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Editar_TbOrdenActionPerformed
        Integer id = (Integer) JT_Tabla_Ordenes.getModel().getValueAt(JT_Tabla_Ordenes.getSelectedRow(), 0);
        OrdenControlador control = new OrdenControlador();
        Orden orden = control.obtenerOrdenPorId(id);
        VistaInsertarOrden vInsertarOrden = new VistaInsertarOrden(orden, this);//inicia la instancia vista insertar cliente en caso de modificar una orden
        vInsertarOrden.setVisible(true);
    }//GEN-LAST:event_jB_Editar_TbOrdenActionPerformed

    private void jB_Editar_TbOrdenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_Editar_TbOrdenMouseClicked

    }//GEN-LAST:event_jB_Editar_TbOrdenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaOrden().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JT_Tabla_Ordenes;
    private javax.swing.JButton jB_Cerrar_TbOrden;
    private javax.swing.JButton jB_Editar_TbOrden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
