/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reto5.vista;

import static java.awt.SystemColor.control;
import javax.swing.JOptionPane;
import reto5.controlador.ClienteControlador;
import reto5.modelo.Cliente;

/**
 *
 * @author Jaiver
 * La siguiente ventana permite al usuario eliminar un Cliente, agregarlo, o modificarlo
 */
public class VistaInsertarCliente extends javax.swing.JFrame {
    Cliente cliente;
    VistaClientes vistaCliente;
    /**
     * Creates new form VistaInssertarCliente
     */
    public VistaInsertarCliente() {
        initComponents();
        jB_Eliminar_Cliente.setVisible(false);
        jL_Insertar_Cliente_Titulo.setText("Ingresar un cliente"); //titulo en caso de agregar un cliente
    }

    //metodos para obtener informacion de las cajas te texto
    public VistaInsertarCliente(Cliente cliente, VistaClientes vistaCliente) {
        initComponents();
        this.cliente = cliente;
        this.jT_Ingresar_Nombre_Cliente.setText(cliente.getCliNombre());
        this.jT_Ingresar_Apellidos_Cliente.setText(cliente.getCliApellido());
        this.jT_Ingresar_Documento_Cliente.setText(String.valueOf(cliente.getCliDocumento()));
        this.jT_Ingresar_Telefono_Cliente.setText(String.valueOf(cliente.getCliTelefono()));
        this.jB_Guardar_Cliente.setText("Actualizar"); //boton en caso de actualizar 
        this.vistaCliente = vistaCliente;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_Nombres_Cliente = new javax.swing.JLabel();
        jT_Ingresar_Nombre_Cliente = new javax.swing.JTextField();
        jL_Apellidos_Cliente = new javax.swing.JLabel();
        jT_Ingresar_Apellidos_Cliente = new javax.swing.JTextField();
        jL_Documento_Cliente = new javax.swing.JLabel();
        jT_Ingresar_Documento_Cliente = new javax.swing.JTextField();
        jL_Telefono_Cliente = new javax.swing.JLabel();
        jT_Ingresar_Telefono_Cliente = new javax.swing.JTextField();
        jB_Guardar_Cliente = new javax.swing.JButton();
        jB_Cerrrar_Ventana_Guardar_Clientes = new javax.swing.JButton();
        jB_Eliminar_Cliente = new javax.swing.JButton();
        jL_Insertar_Cliente_Titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jL_Nombres_Cliente.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jL_Nombres_Cliente.setText("Nombres");

        jT_Ingresar_Nombre_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_Ingresar_Nombre_ClienteActionPerformed(evt);
            }
        });

        jL_Apellidos_Cliente.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jL_Apellidos_Cliente.setText("Apellidos");

        jT_Ingresar_Apellidos_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_Ingresar_Apellidos_Cliente_ClienteActionPerformed(evt);
            }
        });

        jL_Documento_Cliente.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jL_Documento_Cliente.setText("Documento");

        jT_Ingresar_Documento_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_Ingresar_Documento_ClienteActionPerformed(evt);
            }
        });

        jL_Telefono_Cliente.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jL_Telefono_Cliente.setText("Telefono");

        jT_Ingresar_Telefono_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_Ingresar_Telefono_ClienteActionPerformed(evt);
            }
        });

        jB_Guardar_Cliente.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jB_Guardar_Cliente.setText("Guardar");
        jB_Guardar_Cliente.setActionCommand("");
        jB_Guardar_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_Guardar_ClienteMouseClicked(evt);
            }
        });
        jB_Guardar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Guardar_ClienteActionPerformed(evt);
            }
        });

        jB_Cerrrar_Ventana_Guardar_Clientes.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jB_Cerrrar_Ventana_Guardar_Clientes.setText("Cerrar");
        jB_Cerrrar_Ventana_Guardar_Clientes.setMaximumSize(new java.awt.Dimension(71, 23));
        jB_Cerrrar_Ventana_Guardar_Clientes.setMinimumSize(new java.awt.Dimension(71, 23));
        jB_Cerrrar_Ventana_Guardar_Clientes.setPreferredSize(new java.awt.Dimension(71, 23));
        jB_Cerrrar_Ventana_Guardar_Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_Cerrrar_Ventana_Guardar_ClientesMouseClicked(evt);
            }
        });
        jB_Cerrrar_Ventana_Guardar_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Cerrrar_Ventana_Guardar_ClientesActionPerformed(evt);
            }
        });

        jB_Eliminar_Cliente.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jB_Eliminar_Cliente.setText("Eliminar");
        jB_Eliminar_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_Eliminar_ClienteMouseClicked(evt);
            }
        });
        jB_Eliminar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Eliminar_ClienteActionPerformed(evt);
            }
        });

        jL_Insertar_Cliente_Titulo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jL_Insertar_Cliente_Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user (1).png"))); // NOI18N
        jL_Insertar_Cliente_Titulo.setText("Editar/Eliminar un cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_Apellidos_Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jL_Nombres_Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jL_Telefono_Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jL_Documento_Cliente)
                                    .addComponent(jB_Guardar_Cliente))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jT_Ingresar_Telefono_Cliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_Ingresar_Documento_Cliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_Ingresar_Apellidos_Cliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_Ingresar_Nombre_Cliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jB_Eliminar_Cliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(jB_Cerrrar_Ventana_Guardar_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jL_Insertar_Cliente_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jL_Insertar_Cliente_Titulo)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_Ingresar_Nombre_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Nombres_Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_Ingresar_Apellidos_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Apellidos_Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_Ingresar_Documento_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Documento_Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_Ingresar_Telefono_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Telefono_Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Guardar_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Eliminar_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Cerrrar_Ventana_Guardar_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jT_Ingresar_Nombre_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_Ingresar_Nombre_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_Ingresar_Nombre_ClienteActionPerformed

    private void jT_Ingresar_Apellidos_Cliente_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_Ingresar_Apellidos_Cliente_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_Ingresar_Apellidos_Cliente_ClienteActionPerformed

    private void jT_Ingresar_Documento_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_Ingresar_Documento_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_Ingresar_Documento_ClienteActionPerformed

    private void jT_Ingresar_Telefono_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_Ingresar_Telefono_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_Ingresar_Telefono_ClienteActionPerformed

    private void jB_Guardar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Guardar_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_Guardar_ClienteActionPerformed

    private void jB_Guardar_ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_Guardar_ClienteMouseClicked
      //accion del boton en el caso de guardar, obtiene la informacion necesaria de las cajas de texto
        String nombre = jT_Ingresar_Nombre_Cliente.getText();
        String apellido = jT_Ingresar_Apellidos_Cliente.getText();
        Long documento = Long.valueOf(jT_Ingresar_Documento_Cliente.getText());
        Long telefono = Long.valueOf(jT_Ingresar_Telefono_Cliente.getText());
        ClienteControlador control = new ClienteControlador();
        Cliente clienteLocal = new Cliente(nombre, apellido, documento, telefono);
        if(jB_Guardar_Cliente.getText().equals("Actualizar")){
            JOptionPane.showMessageDialog(this,"Se actualizo el cliente");
            control.actualizarCliente(clienteLocal, cliente.getCliId());
            vistaCliente.mostrarClientes();
        }
        else{
            control.insertarCliente(clienteLocal);
            JOptionPane.showMessageDialog(this,"Se guardo el cliente");
        }
        
    }//GEN-LAST:event_jB_Guardar_ClienteMouseClicked

    private void jB_Cerrrar_Ventana_Guardar_ClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_Cerrrar_Ventana_Guardar_ClientesMouseClicked
       this.dispose(); //cierra la ventana
       
    }//GEN-LAST:event_jB_Cerrrar_Ventana_Guardar_ClientesMouseClicked

    private void jB_Cerrrar_Ventana_Guardar_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Cerrrar_Ventana_Guardar_ClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_Cerrrar_Ventana_Guardar_ClientesActionPerformed

    private void jB_Eliminar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Eliminar_ClienteActionPerformed
            
    }//GEN-LAST:event_jB_Eliminar_ClienteActionPerformed

    private void jB_Eliminar_ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_Eliminar_ClienteMouseClicked
        //Elimina un cliente usando el metodo de eliminar
        JOptionPane.showMessageDialog(this,"Se elimino un Cliente");
        ClienteControlador control = new ClienteControlador(); 
        control.eliminarCliente(cliente);
        vistaCliente.mostrarClientes();

      
    }//GEN-LAST:event_jB_Eliminar_ClienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaInsertarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaInsertarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaInsertarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaInsertarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaInsertarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Cerrrar_Ventana_Guardar_Clientes;
    private javax.swing.JButton jB_Eliminar_Cliente;
    private javax.swing.JButton jB_Guardar_Cliente;
    private javax.swing.JLabel jL_Apellidos_Cliente;
    private javax.swing.JLabel jL_Documento_Cliente;
    private javax.swing.JLabel jL_Insertar_Cliente_Titulo;
    private javax.swing.JLabel jL_Nombres_Cliente;
    private javax.swing.JLabel jL_Telefono_Cliente;
    private javax.swing.JTextField jT_Ingresar_Apellidos_Cliente;
    private javax.swing.JTextField jT_Ingresar_Documento_Cliente;
    private javax.swing.JTextField jT_Ingresar_Nombre_Cliente;
    private javax.swing.JTextField jT_Ingresar_Telefono_Cliente;
    // End of variables declaration//GEN-END:variables
}
