/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reto5.vista;

import java.util.List;
import reto5.controlador.TipoPlatoControlador;
import reto5.modelo.TipoPlato;

/**
 *
 * @author Jaiver
 * * El siguiente archivo crea la ventana vista Platos donde se encuentra la tabla de tipo de platos
 */
public class VistaTipoPlato extends javax.swing.JFrame {

    /**
     * Creates new form Vista tipoPlato
     */
    public VistaTipoPlato() {
        initComponents();
        mostrarTipoPlatos();
    }
    
    public void mostrarTipoPlatos(){
        TipoPlatoControlador control = new TipoPlatoControlador();
        List<TipoPlato> tipoplatos = control.obtenerTodosLosTipoPlatos();
        ModeloTablaTipoPlato modeloTabla = new ModeloTablaTipoPlato(tipoplatos);
        JT_Tabla_TipoPlatos.setModel(modeloTabla);
        JT_Tabla_TipoPlatos.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JT_Tabla_TipoPlatos = new javax.swing.JTable();
        jB_Cerrar_TbtipoPlato = new javax.swing.JButton();
        jB_Editar_TbTipoPlato = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(JT_Tabla_TipoPlatos);

        jB_Cerrar_TbtipoPlato.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jB_Cerrar_TbtipoPlato.setText("Cerrar");
        jB_Cerrar_TbtipoPlato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_Cerrar_TbtipoPlatoMouseClicked(evt);
            }
        });
        jB_Cerrar_TbtipoPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Cerrar_TbtipoPlatoActionPerformed(evt);
            }
        });

        jB_Editar_TbTipoPlato.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jB_Editar_TbTipoPlato.setText("Editar");
        jB_Editar_TbTipoPlato.setToolTipText("");
        jB_Editar_TbTipoPlato.setActionCommand("");
        jB_Editar_TbTipoPlato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_Editar_TbTipoPlatoMouseClicked(evt);
            }
        });
        jB_Editar_TbTipoPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Editar_TbTipoPlatoActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/skewer (1).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jB_Editar_TbTipoPlato)
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jB_Cerrar_TbtipoPlato)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jB_Editar_TbTipoPlato)
                        .addComponent(jB_Cerrar_TbtipoPlato)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_Cerrar_TbtipoPlatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_Cerrar_TbtipoPlatoMouseClicked
        this.dispose();
    }//GEN-LAST:event_jB_Cerrar_TbtipoPlatoMouseClicked

    private void jB_Cerrar_TbtipoPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Cerrar_TbtipoPlatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_Cerrar_TbtipoPlatoActionPerformed

    private void jB_Editar_TbTipoPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Editar_TbTipoPlatoActionPerformed
        Integer id = (Integer) JT_Tabla_TipoPlatos.getModel().getValueAt(JT_Tabla_TipoPlatos.getSelectedRow(), 0);
        TipoPlatoControlador control = new TipoPlatoControlador();
        TipoPlato tipoplato = control.obtenerTipoPlatoPorId(id);//inicia la instancia vista insertar cliente en caso de modificar un tipo de plato
        VistaInsertarTipoPlato vInsertarPlato = new VistaInsertarTipoPlato(tipoplato, this);
        vInsertarPlato.setVisible(true);
    }//GEN-LAST:event_jB_Editar_TbTipoPlatoActionPerformed

    private void jB_Editar_TbTipoPlatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_Editar_TbTipoPlatoMouseClicked

    }//GEN-LAST:event_jB_Editar_TbTipoPlatoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaTipoPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaTipoPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaTipoPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaTipoPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaTipoPlato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JT_Tabla_TipoPlatos;
    private javax.swing.JButton jB_Cerrar_TbtipoPlato;
    private javax.swing.JButton jB_Editar_TbTipoPlato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
