/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reto5.vista;

import static java.awt.SystemColor.control;
import javax.swing.JOptionPane;
import reto5.controlador.PlatoControlador;
import reto5.modelo.Plato;

/**
 *
 * @author Jaiver
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 La siguiente ventana permite al usuario eliminar un plato, agregarlo, o modificarlo
 */

public class VistaInsertarPlato extends javax.swing.JFrame {
    Plato plato;
    VistaPlato vistaPlato;
    /**
     * Creates new form VistaInssertarMesero
     */
    public VistaInsertarPlato() {
        initComponents();
        jB_Eliminar_Plato.setVisible(false);
        jL_Insertar_Mesero_Titulo.setText("Ingresar un plato");//titulo en caso de agregar un plato
    }
//metodos para obtener informacion de las cajas te texto
    public VistaInsertarPlato(Plato plato, VistaPlato vistaPlato) {
        initComponents();
        this.plato = plato;
        this.jT_Ingresar_PlatoNombre.setText(plato.getPltNombre());
        this.jT_Ingresar_PlatoPrecio.setText(String.valueOf(plato.getPltPrecio()));
        this.jT_Ingresar_Id_Mesero_Orden.setText(plato.getPltDescripcion());
        this.jT_Ingresar_TipoPlatoId.setText(String.valueOf(plato.getTipoPlatoId()));
        this.jB_Guardar_Plato.setText("Actualizar"); 
        this.vistaPlato = vistaPlato;
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_PlatoNombre = new javax.swing.JLabel();
        jT_Ingresar_PlatoNombre = new javax.swing.JTextField();
        jL_PlatoPrecio = new javax.swing.JLabel();
        jT_Ingresar_PlatoPrecio = new javax.swing.JTextField();
        jL_DescripcionPlato = new javax.swing.JLabel();
        jL_TipoPlatoId = new javax.swing.JLabel();
        jT_Ingresar_TipoPlatoId = new javax.swing.JTextField();
        jB_Guardar_Plato = new javax.swing.JButton();
        jB_Cerrar_Ventana_Guardar_Plato = new javax.swing.JButton();
        jB_Eliminar_Plato = new javax.swing.JButton();
        jL_Insertar_Mesero_Titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_Ingresar_Id_Mesero_Orden = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jL_PlatoNombre.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jL_PlatoNombre.setText("Nombre:");

        jT_Ingresar_PlatoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_Ingresar_PlatoNombreActionPerformed(evt);
            }
        });

        jL_PlatoPrecio.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jL_PlatoPrecio.setText("Precio");

        jT_Ingresar_PlatoPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_Ingresar_PlatoPrecio_ClienteActionPerformed(evt);
            }
        });

        jL_DescripcionPlato.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jL_DescripcionPlato.setText("Descripción");

        jL_TipoPlatoId.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jL_TipoPlatoId.setText("Tipo Plato Id");

        jT_Ingresar_TipoPlatoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_Ingresar_TipoPlatoIdActionPerformed(evt);
            }
        });

        jB_Guardar_Plato.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jB_Guardar_Plato.setText("Guardar");
        jB_Guardar_Plato.setActionCommand("");
        jB_Guardar_Plato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_Guardar_PlatoMouseClicked(evt);
            }
        });
        jB_Guardar_Plato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Guardar_PlatoActionPerformed(evt);
            }
        });

        jB_Cerrar_Ventana_Guardar_Plato.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jB_Cerrar_Ventana_Guardar_Plato.setText("Cerrar");
        jB_Cerrar_Ventana_Guardar_Plato.setMaximumSize(new java.awt.Dimension(71, 23));
        jB_Cerrar_Ventana_Guardar_Plato.setMinimumSize(new java.awt.Dimension(71, 23));
        jB_Cerrar_Ventana_Guardar_Plato.setPreferredSize(new java.awt.Dimension(71, 23));
        jB_Cerrar_Ventana_Guardar_Plato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_Cerrar_Ventana_Guardar_PlatoMouseClicked(evt);
            }
        });
        jB_Cerrar_Ventana_Guardar_Plato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Cerrar_Ventana_Guardar_PlatoActionPerformed(evt);
            }
        });

        jB_Eliminar_Plato.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jB_Eliminar_Plato.setText("Eliminar");
        jB_Eliminar_Plato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_Eliminar_PlatoMouseClicked(evt);
            }
        });
        jB_Eliminar_Plato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Eliminar_PlatoActionPerformed(evt);
            }
        });

        jL_Insertar_Mesero_Titulo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jL_Insertar_Mesero_Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dish-fork-and-knife (1).png"))); // NOI18N
        jL_Insertar_Mesero_Titulo.setText("Editar/Eliminar un Plato");

        jT_Ingresar_Id_Mesero_Orden.setColumns(20);
        jT_Ingresar_Id_Mesero_Orden.setRows(5);
        jScrollPane1.setViewportView(jT_Ingresar_Id_Mesero_Orden);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jL_Insertar_Mesero_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_PlatoPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jL_PlatoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jL_TipoPlatoId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jL_DescripcionPlato)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jB_Guardar_Plato)
                                .addGap(8, 8, 8)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jB_Eliminar_Plato)
                                .addGap(34, 34, 34)
                                .addComponent(jB_Cerrar_Ventana_Guardar_Plato, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jT_Ingresar_TipoPlatoId, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(jT_Ingresar_PlatoPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(jT_Ingresar_PlatoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1))))
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jL_Insertar_Mesero_Titulo)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_Ingresar_PlatoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_PlatoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_Ingresar_PlatoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_PlatoPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_Ingresar_TipoPlatoId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_TipoPlatoId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jL_DescripcionPlato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Guardar_Plato, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Eliminar_Plato, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Cerrar_Ventana_Guardar_Plato, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jT_Ingresar_PlatoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_Ingresar_PlatoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_Ingresar_PlatoNombreActionPerformed

    private void jT_Ingresar_PlatoPrecio_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_Ingresar_PlatoPrecio_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_Ingresar_PlatoPrecio_ClienteActionPerformed

    private void jT_Ingresar_TipoPlatoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_Ingresar_TipoPlatoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_Ingresar_TipoPlatoIdActionPerformed

    private void jB_Guardar_PlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Guardar_PlatoActionPerformed
        String PltNombre = jT_Ingresar_PlatoNombre.getText();
        long PltPrecio = Long.valueOf(jT_Ingresar_PlatoPrecio.getText());
        String PltDescripcion = jT_Ingresar_Id_Mesero_Orden.getText();
        int TipoPlatoId = Integer.valueOf(jT_Ingresar_TipoPlatoId.getText());
     
        PlatoControlador control = new PlatoControlador();
        Plato platoLocal = new Plato(PltNombre, PltPrecio, PltDescripcion, TipoPlatoId);
        if(jB_Guardar_Plato.getText().equals("Actualizar")){
            control.actualizarPlato(platoLocal,plato.getPltId());
            vistaPlato.mostrarPlatos();
             JOptionPane.showMessageDialog(this,"Se actualizo un plato");
        }
        else{
            control.insertarPlato(platoLocal);
             JOptionPane.showMessageDialog(this,"Se guardo un plato");
        }
    }//GEN-LAST:event_jB_Guardar_PlatoActionPerformed

    private void jB_Guardar_PlatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_Guardar_PlatoMouseClicked
  
    }//GEN-LAST:event_jB_Guardar_PlatoMouseClicked

    private void jB_Cerrar_Ventana_Guardar_PlatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_Cerrar_Ventana_Guardar_PlatoMouseClicked
       this.dispose();
       
    }//GEN-LAST:event_jB_Cerrar_Ventana_Guardar_PlatoMouseClicked

    private void jB_Cerrar_Ventana_Guardar_PlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Cerrar_Ventana_Guardar_PlatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_Cerrar_Ventana_Guardar_PlatoActionPerformed

    private void jB_Eliminar_PlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Eliminar_PlatoActionPerformed
                        
    }//GEN-LAST:event_jB_Eliminar_PlatoActionPerformed

    private void jB_Eliminar_PlatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_Eliminar_PlatoMouseClicked
         JOptionPane.showMessageDialog(this,"Se elimino un Plato");
        PlatoControlador control = new PlatoControlador();
        control.eliminarPlato(plato);
        vistaPlato.mostrarPlatos();
        JOptionPane.showMessageDialog(this,"Se elimino el plato");
    
    }//GEN-LAST:event_jB_Eliminar_PlatoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaInsertarPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaInsertarPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaInsertarPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaInsertarPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaInsertarPlato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Cerrar_Ventana_Guardar_Plato;
    private javax.swing.JButton jB_Eliminar_Plato;
    private javax.swing.JButton jB_Guardar_Plato;
    private javax.swing.JLabel jL_DescripcionPlato;
    private javax.swing.JLabel jL_Insertar_Mesero_Titulo;
    private javax.swing.JLabel jL_PlatoNombre;
    private javax.swing.JLabel jL_PlatoPrecio;
    private javax.swing.JLabel jL_TipoPlatoId;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jT_Ingresar_Id_Mesero_Orden;
    private javax.swing.JTextField jT_Ingresar_PlatoNombre;
    private javax.swing.JTextField jT_Ingresar_PlatoPrecio;
    private javax.swing.JTextField jT_Ingresar_TipoPlatoId;
    // End of variables declaration//GEN-END:variables
}
