/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reto5.vista;

import static java.awt.SystemColor.control;
import javax.swing.JOptionPane;
import reto5.controlador.TipoPlatoControlador;
import reto5.modelo.TipoPlato;

/**
 *
 * @author Jaiver
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 La siguiente ventana permite al usuario eliminar un Cliente, agregarlo, o modificarlo*/

public class VistaInsertarTipoPlato extends javax.swing.JFrame {
    TipoPlato tipoplato;
    VistaTipoPlato vistaTipoPlato;
    /**
     * Creates new form VistaInssertarMesero
     */
    public VistaInsertarTipoPlato() {
        initComponents();
        jB_Eliminar_TipoPlato.setVisible(false);
        jL_Insertar_Mesero_Titulo.setText("Ingresar un tipo de plato");//titulo en caso de agregar un tipo de plato
    }
//metodos para obtener informacion de las cajas te texto
    public VistaInsertarTipoPlato(TipoPlato tipoplato, VistaTipoPlato vistaTipoPlato) {
        initComponents();
        this.tipoplato = tipoplato;
        this.jT_NombreTipoPlato.setText(tipoplato.getTipoPlatoNombre());
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_Nombre = new javax.swing.JLabel();
        jT_NombreTipoPlato = new javax.swing.JTextField();
        jB_Guardar_TipoPlato = new javax.swing.JButton();
        jB_Cerrar_Ventana_Guardar_TipoPlato = new javax.swing.JButton();
        jB_Eliminar_TipoPlato = new javax.swing.JButton();
        jL_Insertar_Mesero_Titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jL_Nombre.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jL_Nombre.setText("Nombre:");

        jT_NombreTipoPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_NombreTipoPlatoActionPerformed(evt);
            }
        });

        jB_Guardar_TipoPlato.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jB_Guardar_TipoPlato.setText("Guardar");
        jB_Guardar_TipoPlato.setActionCommand("");
        jB_Guardar_TipoPlato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_Guardar_TipoPlatoMouseClicked(evt);
            }
        });
        jB_Guardar_TipoPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Guardar_TipoPlatoActionPerformed(evt);
            }
        });

        jB_Cerrar_Ventana_Guardar_TipoPlato.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jB_Cerrar_Ventana_Guardar_TipoPlato.setText("Cerrar");
        jB_Cerrar_Ventana_Guardar_TipoPlato.setMaximumSize(new java.awt.Dimension(71, 23));
        jB_Cerrar_Ventana_Guardar_TipoPlato.setMinimumSize(new java.awt.Dimension(71, 23));
        jB_Cerrar_Ventana_Guardar_TipoPlato.setPreferredSize(new java.awt.Dimension(71, 23));
        jB_Cerrar_Ventana_Guardar_TipoPlato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_Cerrar_Ventana_Guardar_TipoPlatoMouseClicked(evt);
            }
        });
        jB_Cerrar_Ventana_Guardar_TipoPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Cerrar_Ventana_Guardar_TipoPlatoActionPerformed(evt);
            }
        });

        jB_Eliminar_TipoPlato.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jB_Eliminar_TipoPlato.setText("Eliminar");
        jB_Eliminar_TipoPlato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_Eliminar_TipoPlatoMouseClicked(evt);
            }
        });
        jB_Eliminar_TipoPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Eliminar_TipoPlatoActionPerformed(evt);
            }
        });

        jL_Insertar_Mesero_Titulo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jL_Insertar_Mesero_Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/skewer (1).png"))); // NOI18N
        jL_Insertar_Mesero_Titulo.setText("Editar/Eliminar un Tipo de Plato");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jL_Insertar_Mesero_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jB_Guardar_TipoPlato)
                                .addGap(8, 8, 8)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jB_Eliminar_TipoPlato)
                                .addGap(34, 34, 34)
                                .addComponent(jB_Cerrar_Ventana_Guardar_TipoPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jT_NombreTipoPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jL_Insertar_Mesero_Titulo)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_NombreTipoPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Guardar_TipoPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Eliminar_TipoPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Cerrar_Ventana_Guardar_TipoPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jT_NombreTipoPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_NombreTipoPlatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_NombreTipoPlatoActionPerformed

    private void jB_Guardar_TipoPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Guardar_TipoPlatoActionPerformed
        String TipoPltNombre = jT_NombreTipoPlato.getText();
        
     
        TipoPlatoControlador control = new TipoPlatoControlador();
        TipoPlato TipoPlatoLocal = new TipoPlato(TipoPltNombre);
        if(jB_Guardar_TipoPlato.getText().equals("Actualizar")){
            control.actualizarTipoPlato(TipoPlatoLocal,tipoplato.getTipoPlatoId());
            vistaTipoPlato.mostrarTipoPlatos();
             JOptionPane.showMessageDialog(this,"Se actualizo un tipo de plato");
        }
        else{
             JOptionPane.showMessageDialog(this,"Se guardo un tipo de plato");
            control.insertarTipoPlato(TipoPlatoLocal);
        }
    }//GEN-LAST:event_jB_Guardar_TipoPlatoActionPerformed

    private void jB_Guardar_TipoPlatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_Guardar_TipoPlatoMouseClicked
  
    }//GEN-LAST:event_jB_Guardar_TipoPlatoMouseClicked

    private void jB_Cerrar_Ventana_Guardar_TipoPlatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_Cerrar_Ventana_Guardar_TipoPlatoMouseClicked
       this.dispose();
       
    }//GEN-LAST:event_jB_Cerrar_Ventana_Guardar_TipoPlatoMouseClicked

    private void jB_Cerrar_Ventana_Guardar_TipoPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Cerrar_Ventana_Guardar_TipoPlatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_Cerrar_Ventana_Guardar_TipoPlatoActionPerformed

    private void jB_Eliminar_TipoPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Eliminar_TipoPlatoActionPerformed
                        
    }//GEN-LAST:event_jB_Eliminar_TipoPlatoActionPerformed

    private void jB_Eliminar_TipoPlatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_Eliminar_TipoPlatoMouseClicked
        JOptionPane.showMessageDialog(this,"Se elimino un Plato");
        TipoPlatoControlador control = new TipoPlatoControlador();
        control.eliminarTipoPlato(tipoplato);
        vistaTipoPlato.mostrarTipoPlatos();
         JOptionPane.showMessageDialog(this,"Se elimino el tipo de plato");
 
    }//GEN-LAST:event_jB_Eliminar_TipoPlatoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaInsertarTipoPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaInsertarTipoPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaInsertarTipoPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaInsertarTipoPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaInsertarTipoPlato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Cerrar_Ventana_Guardar_TipoPlato;
    private javax.swing.JButton jB_Eliminar_TipoPlato;
    private javax.swing.JButton jB_Guardar_TipoPlato;
    private javax.swing.JLabel jL_Insertar_Mesero_Titulo;
    private javax.swing.JLabel jL_Nombre;
    private javax.swing.JTextField jT_NombreTipoPlato;
    // End of variables declaration//GEN-END:variables
}
